### ISSUE TITLE
Add support for EIP-2612

### ISSUE THREAD

**Issue by rube-de** [aktionariat/contracts#106]

**Comment by muratogat** [comment]
Why are we using this and not https://eips.ethereum.org/EIPS/eip-2771 ? 
Seems more straightforward.

**Comment by luziusmeisser** [comment]
I suggest to:

1. We hardcode an infinite allowance for the permit2 contract into our tokens.
2. Then use permit2, https://github.com/Uniswap/permit2

**Comment by luziusmeisser** [comment]
All we would need to do is add the bold lines to our ERC20 contract:

function transferFrom(address sender, address recipient, uint256 amount) external override returns (bool) {
        _transfer(sender, recipient, amount);
        **if (msg.sender != PERMIT2_CONTRACT){**
            uint256 currentAllowance = _allowances[sender][msg.sender];
            if (currentAllowance < (1 << 255)){
                // Only decrease the allowance if it was not set to 'infinite'
                // Documented in /doc/infiniteallowance.md
                require(currentAllowance >= amount, "approval not enough");
                _approve(sender, msg.sender, currentAllowance - amount);
            }
        **}**
        return true;
    }
