### ISSUE TITLE
Brokerbot should emit events for in-and out-flow of ETH

### ISSUE THREAD

**Issue by luziusmeisser** [aktionariat/contracts#115]
Due to a lack of transfer events when Ethers are sent around, it is currently very hard to figure out whether a sale was against Ether (with keep Ether) or XCHF. Paymenthub should emit an event when a sale with "keep ether" was processed.

For example:

event EtherKept(uint256 etheramount, uint256 xchfamount)

This would allow us to create better accounting reports.

**Comment by luziusmeisser** [comment]
Alternatively, we could add additional data to the trade reference blob. This would be less user-friendly to look at on etherscan, but much faster to process by the backend.

**Comment by luziusmeisser** [comment]
Also, we should emit an event when ETH is received or withdrawn, so we can properly track balances.

**Comment by rube-de** [comment]
> Also, we should emit an event when ETH is received or withdrawn, so we can properly track balances.

this means on the brokerbot contract level?

**Comment by luziusmeisser** [comment]
Yes, this should be in the Brokerbot contract. Maybe we should also introduce similar methods on the Multisig contract, so we can track the Ether flows in and out. But this should be in a separate issue.

**Comment by rube-de** [comment]
>  Maybe we should also introduce similar methods on the Multisig contract, so we can track the Ether flows in and out. But this should be in a separate issue.
The multisig has an event for receiving ETH. For sending we could emit one if the execute function includes a value > 0

**Comment by rube-de** [comment]
> Yes, this should be in the Brokerbot contract. 

I suggest we rename this issue to "Brokerbot should emit events for in-and out-flow of ETH" (like you also described the problem in slack) and emit events in the brokerbot on processIncoming and withdrawEther.
