### ISSUE TITLE
Deploy Internal Test Company

### ISSUE THREAD

**Issue by muratogat** [aktionariat/contracts#146]
multisig first owner - 0xdcaa50578efe0a2ab95767a6dc41d104d543e8d9 - murat.aktionariat.eth
share name - Internal Test Company Shares
share symbol/ticker - INTES - INTESS
terms url - https://www.aktionariat.com/terms-of-service
number of shares - 1'000'000
chain - mainnet

@KostasZav please confirm

**Comment by KostasZav** [comment]
Symbol should be max 5 letters I think, so maybe TEST - TESTS (draggable) would be more suitable.

Other than that looks good

**Comment by rube-de** [comment]
What company it should be linked to?

**Comment by muratogat** [comment]
TEST token already exists.

**Comment by muratogat** [comment]
Dashboard doesn't allow creating a ticker with 6 letters. Going with INTES. Modified the issue.

**Comment by muratogat** [comment]
Company name: Internal Test Company
https://api.aktionariat.com/token?ticker=INTES

**Comment by rube-de** [comment]
Contracts are deployed.
Can't register the token as 5chars max limit and INTESS is 6.

**Comment by muratogat** [comment]
I will contact Piotr to increase limit to 6
