### ISSUE TITLE
Update RecoveryHub with assisted recovery functionality

### ISSUE THREAD

**Issue by muratogat** [aktionariat/contracts#151]
Update RecoveryHub where
- there is a recoveryAdmin address that is set during deployment but can be changed later by the same address
- the recoveryAdmin can create a claim with an arbitrary claimant, no collateral (share address could be used as collateralAddress) and 0 claim period (TBD, could be set to something like 24 or 72 hours as well),
- during claim creation, recoveryAdmin also specifies an alternative addess that can call recover(), which needs to be set to the company multisig address
- The RecoveryHub accepts recover() from being called by the specified company multisig for the claim and moves the tokens to the new address. It should not try to send back collateral in this case.

Above is the initial proposal. Happy to discuss and modify final architecture if needed.

**Comment by rube-de** [comment]
* There is no reason do a recover instantly, there should be always a time-lock.
* The recover should be called from share token, where the company multisig is owner/oracle

**Comment by KostasZav** [comment]
@muratogat I'm closing this issue for now. We can reopen if needed.
