### ISSUE TITLE
Update deployment script to specify recovery mechanism

### ISSUE THREAD

**Issue by muratogat** [aktionariat/contracts#152]
The backend needs to keep track of which recovery mechanism is supported by which token.

Currently we should have 
- NONE -> No recovery available
- TOKEN -> The recovery function is available on the draggable token itself
- RECOVERYHUB -> The recovery function is available through RecoveryHub contract

The assisted function should add a new one
+ RECOVERYHUB_ASSISTED -> Token supports the new RecoveryHub that allows assisted recovery
Note that for RECEOVERYHUB_ASSISTED, the original decentralized recovery mechanism will still continue to be available. 

I think the best way to keep track of it is to set it during the deployment script. I will link the related backend issue here.

**Comment by KostasZav** [comment]
Closing this as well and can reopen if we really need it.
