### ISSUE TITLE
Better deployment practices & documentation.

### ISSUE THREAD

**Issue by muratogat** [aktionariat/contracts#16]
(For Bernhard)
We need a better smart contract deployment process, that allows us to integrate some tests (ensuring latest compiler, correct number of optimizations, etc.) and make dry-runs.
Note that for many contracts, there exists a Java function in the backend that deploys it and also makes the necessary changes in the backend (such as deploying a token and adding it to the DB). 
We can have better documentation on how to deploy any of our contracts, when to do it through the backend and the effects in the DB when doing so.

**Comment by muratogat** [comment]
As @rube-de suggested, currently considering a move to HardHat https://hardhat.org/ , as this is what the best teams are using, and works better than truffle with L2 solution.

@rube-de could you check how it would work with our contracts? You could make a "hardhat" branch of this repo and restructure it as you will. Note that we may want to keep the contracts and tests still in separate repos.

**Comment by rube-de** [comment]
@muratogat I don't think we need to touch the contracts regarding hardhat, except we want to use hardhat to compile instead of manually compile.
I would like to discuss the pro/cons of having the separate test repo. having one repo for the contracts would make CI easier, as we can compile/test/make security checks/log gas usage in one go/on PR with CI tools like Travis

**Comment by bladekp** [comment]
As a CI tool, instead of travis, we can go with github actions, I can help setting this up

**Comment by muratogat** [comment]
Since we are already heavily on GitHub, I would prefer GitHub actions, but only if they provide the same functionality we would get from Travis. Can both work with Solidity, or is that language agnostic?

**Comment by rube-de** [comment]
Yes I guess github actions works too, Uniswap and others using it too.

**Comment by luziusmeisser** [comment]
Regarding deployment of client contracts, we also need to think about:
- How to verify them on etherscan
- How to add custom icons and a project URL (requires ownership verification)
- Add them to the database

The first two steps probably can't be automated, but at least they should be documented.

**Comment by muratogat** [comment]
I think:
- Verifying on etherscan should be part of the deployment process. There should be scripts that take care of this automatically after the contract is deployed.
- To make the deployment also make the changes necessary in the database, we could provide some endpoints that take the necessary parameters and make the updates. So almost the current structure - the deployment, able to be called from outside. Of course we need to think about authentication for those endpoints.
