### ISSUE TITLE
setTotalShares missing in some contracts

### ISSUE THREAD

**Issue by KostasZav** [aktionariat/contracts#194]
For some of the deployed tokens, the function setTotalShares is missing. We should inspect, find all the affected tokens and discuss in a short meeting the next steps.

See QTS --> https://etherscan.io/address/0xAe7c2042c2f84Ff5880A185Bd7D81dA5B822B3A7#code
as opposed to PEX --> https://polygonscan.com/address/0xce10ce11e5001dde681a6a986664143545845d45#code#F1#L97

**Comment by rube-de** [comment]
There are few all contracts deployed before 2022, which don't emit an event for this function. 
We'll have to track them different in our backend (info for that in https://github.com/aktionariat/backend/issues/1169 )
