### ISSUE TITLE
Bond with continuous issuance and redemption

### ISSUE THREAD

**Issue by luziusmeisser** [aktionariat/contracts#21]
We would like to have a bond token that is continuously issued and repurchased within some given bounds and at a deterministically given price that changes over time. The bond is a zero bond, so it starts at a value of e.g. 0.50 USD and ends at a value of 1.00 USD at maturity. At maturity, the bond becomes redeemable with the issuer, whereas redemption is triggered by the individual shareholders and not forcefully executed by the issuer.

**Comment by luziusmeisser** [comment]
Bond terms could be:

- Maturity: 5000 days
- Issuance volume: up to 3'550'000 - 300*t units
- Issuance price: 0.58 + 0.000084*t
- Implied approximate interest: 4%
- Early redemption: the issuer reserves some liquidity for early redemptions at the issuance price. This liquidity pool is periodically filled with available cash from ongoing operations at the discretion of the issuer.
- Equal treatment: if there is more interest in the market for early redemption than the liquidity reserve allows (i.e. the redemption reserve is empty), the issuer refrains from adding liquidity to the redemption reserve without making sure that the bond holders have an equal chance at redeeming their (or a part of their) bonds early. This could for example be achieved by having a reverse auction, in which the newly available liquidity is given to whoever bond holders is offering the most units of the bonds in exchange.

**Comment by KostasZav** [comment]
Closing this issue following the daily IT meeting discussion (10/05).
