### ISSUE TITLE
Restructure / cleanup folders

### ISSUE THREAD

**Issue by rube-de** [aktionariat/contracts#35]
As a developer I want to have a better overview and structure.

* structure the contracts folder to not have everything flat
* test folder => linked with remove truffe issue
* deploy folder: group better / prepare for l2?

**Comment by muratogat** [comment]
+1 for this but what is the ideal structure?
There may be hardcoded links somewhere, like other repos or Java code. 
Also I think both hardhat and truffle compile just whatever is in a directory. Do they compile also subdirectories?
