### ISSUE TITLE
Configure Brokerbot to keep ETH

### ISSUE THREAD

**Issue by luziusmeisser** [aktionariat/contracts#36]
We should allow issuers to keep the ETH when selling shares instead of exchanging them on uniswap.

The problem is that we have to rely on an ETH-CHF oracle somehow. Not sure if that exists.

An alternative approach could be a "clawback clause", which would allow the issuer to claw the sold shares back (or the xchf in case of a sale) for 72 hours in case of exchange rate manipulation.

Technically, this could work with a small lockup-contract that wraps the returns token and which is automatically released on the next transfer (given that the 72 hours have passed). Further, there would be an arbiter address defined belonging to a notary or so that could in case of a exchange rate manipulation return the shares or sales proceeds to the issuer.

Of course, such a setup wouldn't be trustless any more, but it would allow us to accept arbitrary currencies. Further, it is still possible to go trustless for those users that use CHF directly.

**Comment by rube-de** [comment]
if we rely on Uniswap to trade ETH-xCHF we can also use Uniswap as the oracle. See:
https://docs.uniswap.org/protocol/V2/guides/smart-contract-integration/building-an-oracle

**Comment by luziusmeisser** [comment]
When trading ETH XCHF, there is no risk. the company always gets the desired amount of XCHF. all the exchange rate risk is with the buyer.

I think Uniswap does not offer Oracle by default. this is something that has to be maintained by someone, right?

**Comment by muratogat** [comment]
Should we give the option to the client, whether they want to keep the ETH or sell it for XCHF immediately? Then we would need to support both.
I am not so much scared of price manipulation. Especially in Uniswap, they are now using weighted averages that prevents basic attacks. It's exchange rate could be used as an oracle in general. @rube-de do you see any risks with that?
If we are going to use an oracle, I would use Chainlink since it's the most established one. Could be a bit overkill for us though.

**Comment by luziusmeisser** [comment]
yes, it would be a setting for the client

**Comment by muratogat** [comment]
Then I think we need :
- An update for PaymentHub, that is similar to payFromEtherAndNotify, gets the required ETH but doesn't actually execute the swap (payWithEtherAndNotify?)
- An update to the Brokerbot, that can get notified by the PaymentHub and sends out the necessary shares
- An update to the Brokerbot to withdraw ETH from it (or is this already possible?)
