### ISSUE TITLE
Sell against Ether and other Tokens

### ISSUE THREAD

**Issue by luziusmeisser** [aktionariat/contracts#47]
I think this is best done as a brokerbot update.

In order to prevent the user from having to do an approval transaction first, this could be implemented using the IERC-667 notifications with our type flags.

Let's say, we use the first byte of the reference number to indicate the desired currency of the seller. 0x03 could be an ether sale. In that case, the Brokerbot would have to consult with the payment hub to get the right amount of Ether and then send them to the seller. That way we are flexible to change the oracle without updating all brokerbots. At the same time, we should define the next 100 flags or so to be other tokens we support, e.g. USDC. In that case, the PaymentHub would be called with a method along the lines of "sendCorrectTokenAmount(uint256 chfAmount, bytes1 token, address recipient)". In that method, payment hub would convert the chfAmount into the correct token amount of the token type and then send that to the recipient using Brokerbot.withdraw 

There is one more type of sales, namely selling by bank transfer. This comes with the problem that we do not actually know if the company has enough capital to pay for the shares! I'm accordingly hesitant to implement it. In that case, the Brokerbot would already support it, but it would require some frontend and backend work (e.g. allowing users to specify their IBAN).

**Comment by KostasZav** [comment]
According to @rube-de this is merged
