### ISSUE TITLE
Deploy Quitt Brokerbot w/o fee

### ISSUE THREAD

**Issue by rube-de** [aktionariat/contracts#72]
A new brokerbot w/o fee needs to be deployed for the Quitt shares after the split

multisig: 0x31fa63132841785194C7F0fa1Daf2F4cb01b985A
shares: 0x8747a3114Ef7f0eEBd3eB337F745E31dBF81a952
paymenthub: 0xfb330379134EA1EfCE9Cf6F28E2CcB917899e007

price: 6.00 XCHF (6000000000000000000)
increment: 0.00003 XCHF (30000000000000)

**Comment by luziusmeisser** [comment]
It's deployed. Also the migration function worked well.
