### ISSUE TITLE
Sweep tokens function in share contracts

### ISSUE THREAD

**Issue by rube-de** [aktionariat/contracts#74]
Right now we have a withdraw function on brokerbot and a recover function in the paymenthub to recover erc20 tokens directly to the contract (like xchf).
The shares contract should also have a function callable from an admin to recover wrongly send erc20 tokens directly to the contract.

**Comment by luziusmeisser** [comment]
No, this is not a good idea. The recovery function stores the placed collateral on the token contract, so the sweep function could be abused to steal the recovery collateral. Also, there is no trivial way to find out how much collateral there currently should be on the token. So I suggest to not implement this feature.
