### ISSUE TITLE
DeclareLost / test old contracts

### ISSUE THREAD

**Issue by KostasZav** [aktionariat/contracts#88]
We want to test the scenario of calling the declarelost function directly from the smart contracts for the "old contracts" and check who will be notified via email. We need to test DEXA shares as discussed. Based on the outcome of the testing, we will define the next steps (e.g notify address owner, company's representative, a group of people in Aktionariat etc.)

**Comment by luziusmeisser** [comment]
Note that I reserved some time tomorrow morning to enable these notifications also for the new smart contracts. So we should be close to be able to test it for all tokens.

**Comment by KostasZav** [comment]
> 

@luziusmeisser can you please let us know when this is ready to be tested? Thanks!

**Comment by KostasZav** [comment]
@luziusmeisser is this ready to be tested?

**Comment by Jennykoz** [comment]
Bernard and I tested this issue- 
When old contract is declared lost it seemed that all shareholder or admins are getting notified , with DEXA it seems everyone is both
