### ISSUE TITLE
DeclareLost / test new contracts

### ISSUE THREAD

**Issue by KostasZav** [aktionariat/contracts#89]
We want to test the scenario of calling the declarelost function directly from the smart contracts for the "new contracts" and check who will be notified via email. We will test OES shares as discussed. Based on the outcome of the testing, we will define the next steps (e.g notify address owner, company's representative, a group of people in Aktionariat etc.)

**Comment by Jennykoz** [comment]
Bernard and I tested this issue-
When new contract is declared lost no one received any email

**Comment by KostasZav** [comment]
@rube-de can you please provide an update here and close the ticket once done? Thanks

**Comment by rube-de** [comment]
Email is now send out on declare lost, also on optimism
