### ISSUE TITLE
DeclareLost / check if it has ever been called

### ISSUE THREAD

**Issue by KostasZav** [aktionariat/contracts#91]
As discussed, we need to check if the declarelost function has ever been called for both the "old" & "new" SCs (most importantly for the new ones). Please share with us the outcome, thanks!

**Comment by luziusmeisser** [comment]
Actually, I'm in the process of running a blockchain scan with the latest version of the backend. Nonetheless, it might be good to double check manually.

One contract with a known claim event is the old DSHS token from Quitt.

**Comment by rettichschnidi** [comment]
I just bought some shares from Wemakit. Does this mean my money will be on the line? Will I (or the public for that matter) be able to review the code you will write for the Wemakeit upfront?

**Comment by luziusmeisser** [comment]
The code for the tokens we deploy is open source an in this repository. A good starting point to see what it is capable of is the readme file: https://github.com/aktionariat/contracts/blob/master/README.md
No special changes are needed for wemakeit.

As far as I remember, the wemakeit shares will have the recovery feature and be draggable, but no allowlisting.

**Comment by luziusmeisser** [comment]
Btw: outcome of the above test was that it was never called and that the notifications work.
