### ISSUE TITLE
notifyTradeAndTransfer should not require buyingEnabled

### ISSUE THREAD

**Issue by muratogat** [aktionariat/contracts#96]
Problem: 
The company can't send shares from the Brokerbot through proposals&multisig when buying is disabled. 
As this is something triggered by the company itself, we should allow calling notifyTradeAndTransfer even if buying is disabled.

Diagnosis:
notifyTradeAndTransfer calls notifyTraded, which has require(hasSetting(BUYING_ENABLED));
notifyTradeAndTransfer is onlyOwner
notifyTraded is internal
The only place where notifyTraded() is called seems to be buy(), so this check may as well be done in buy() method instead.
processIncoming coming from PaymentHub also calls "buy()" so I don't see any gap that allows buying externally while buying is disabled
Buy please analyse further and make sure before implementing.

**Comment by rube-de** [comment]
That is already changed in the current version of the brokerbot contract.
